# Generated by Django 4.2.3 on 2023-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('dp', models.FileField(upload_to='user')),
            ],
        ),
    ]
